 1 contributor
26 lines (22 sloc)  589 Bytes

name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as svg"
author: "platane"

runs:
  using: node16
  main: dist/index.js

inputs:
  github_user_name:
    description: "Joao-Eduardo-AJ"
    required: true
  outputs:
    required: false
    default: null
    description: |
